# Parâmetros da pipeline
sample_frac: null     # use um número (ex.: 0.1) para amostrar 10%, ou null para desligar
reports_dir: "data/08_reporting"
forecast_horizon: 6           # quantos cycles futuros avaliar (e quantos finais virarão teste)
seasonal_periods: 12          # ajuste conforme a sazonalidade dos seus cycles
random_seed: 123


# conf/base/parameters/forecast.yml
forecast:
  # parâmetros compartilhados
  common:
    target_col: qty
    min_train: 6

  # controla horizonte e sazonalidade usados em todos
  selection:
    forecast_horizon: 3
    seasonal_periods: 6

  naive:
    horizon: 3
    target_col: qty
    min_train: 6

  holt_winters:
    horizon: 3
    target_col: qty
    min_train: 6
    trend: add            # add | mul
    seasonal: add         # add | mul | null
    seasonal_periods: 6

  sarimax:
    horizon: 3
    target_col: qty
    min_train: 6
    order: [1, 1, 1]
    seasonal_order: [1, 0, 1, 6]
    seasonal_periods: 6

  xgb:
    horizon: 3
    target_col: qty
    min_train: 6
    lags: 6
    random_seed: 123
    n_estimators: 400
    learning_rate: 0.05
    max_depth: 4
    subsample: 0.8
    colsample_bytree: 0.9

  prophet:
    horizon: 3
    target_col: qty
    min_train: 6
    monthly_start: "2000-01-31"

  tuning:
    forecast_horizon: 3
    seasonal_periods: 6